### PR TITLE
fix(home-manager/kvantum): don't uppercase accents and flavors in override

### LINKED ISSUE #357: [Qt] Invalid accent name for Kvantum
Hello, when building my configuration with the home manager module I get the following error, `error: catppuccin-kvantum: theme accent: Pink unexpected; valid ones: blue, flamingo, green, lavender, maroon, mauve, peach, pink, red, rosewater, sapphire, sky, teal, yellow`. I have my accent correctly set as lowercase "pink" and the same issue happens if I enter any other color for the accent. 

I believe this is where the issue occurs.

```
       … while calling a functor (an attribute set with a '__functor' attribute)
         at /nix/store/9q45pahakc5lygxhhcawcb9p7yv6j7fr-source/modules/home-manager/kvantum.nix:13:11:
           12|   accentCapitalized = lib.ctp.mkUpper cfg.accent;
           13|   theme = pkgs.catppuccin-kvantum.override {
             |           ^
           14|     accent = accentCapitalized;

``` 

Here is the configuration I am using for the home manager module.

```nix
catppuccin = {
    flavor = "mocha";
    accent = "pink";
    enable = true;
};

qt = {
    enable = true;

    platformTheme.name = "kvantum";
    style = {
        name = "kvantum";
    };
};

```

### PR DESCRIPTION
**Pull request by ryand56**
Fix for kvantum module, which uses an updated catppuccin-kvantum package that changed from uppercase enums to lowercase.

Closes #357

### CODE REVIEW

**Comment by AxerTheAxe** [comment]
I was working on a PR with these same changes but found that it does not install the kvantum theme for me. Can you confirm that the issue is fixed and that the theme correctly installs for you?

**Comment by ryand56** [comment]
> I was working on a PR with these same changes but found that it does not install the kvantum theme for me. Can you confirm that the issue is fixed and that the theme correctly installs for you?

Oh yeah, theme didn't correctly install for me either.

**Comment by AxerTheAxe** [comment]
Yep, works for me. Thanks!

**Review by isabelroses — COMMENTED** [review]
This won't work since catppuccin/nix supports nixpkgs 24.05 still.

**Comment by ryand56** [comment]
> This won't work since catppuccin/nix supports nixpkgs 24.05 still.

This should only apply now if the version is at least 24.11.

**Comment by AxerTheAxe** [comment]
@isabelroses sorry for the @ but this PR has been updated and is ready for review.

**Comment by isabelroses** [comment]
> @isabelroses sorry for the @ but this PR has been updated and is ready for review.

I can't merge but LGTM, better waiting for getchoo though.

**Comment by sgoudham** [comment]
> I can't merge but LGTM, better waiting for getchoo though.

By the power vested in me, I now pronounce you maintainer of catppuccin/nix 

image

**Comment by isabelroses** [comment]
Thanks for the fix :)

**Pull request merged**
