### PR TITLE
feat(home-manager): init yazi module

### PR DESCRIPTION
**Pull request by michaelBelsanti**

### CODE REVIEW

**Review by getchoo — CHANGES_REQUESTED** [review]
the programs.yazi options will need to be enabled in test.nix

**Comment by michaelBelsanti** [comment]
fixed

**Review by getchoo — APPROVED** [review]
thanks!

**Comment by uncenter** [comment]
I'm new to Nix but it might be nice to somehow detect the shell and offer to enable/define the [`ya` wrapper function](https://yazi-rs.github.io/docs/quick-start#shell-wrapper)?

**Comment by michaelBelsanti** [comment]
Home-manager actually already has that feature: https://home-manager-options.extranix.com/?query=yazi.enable*Integration&release=master

**Comment by uncenter** [comment]
Oh sweet right, I forgot that this is just theming for a sec. Thanks!

**Pull request merged**
