### PR TITLE
feat(mako): add accent color support

### PR DESCRIPTION
**Pull request by SchweGELBin**
I created a pr in catppuccin/mako to add accent color support.
I don't know if it will get merged, but if it will, I can update the sources and it will be available here too.
If it doesn't, just ignore this pr.

This pr is also like a "reminder" to let you know that mako might "break" if the ipstream pr gets merged but this doesn't.

### CODE REVIEW

**Comment by SchweGELBin** [comment]
I meant [this](https://github.com/catppuccin/mako/pull/8) pr

**Comment by SchweGELBin** [comment]
Everything is ready to be merged now. 😁

**Comment by SchweGELBin** [comment]
I made a little mistake, but everything is working as expected now (tested it).

**Review by getchoo — APPROVED** [review]
Awesome work adding this upstream :)

**Pull request merged**
