### PR TITLE
feat(home-manager): add support for hyprlock

### PR DESCRIPTION
**Pull request by 42Willow**
Almost identical to the hyprland home manager module, links the catppuccin source file so colour variables can be used in the config. 
image

https://github.com/catppuccin/hyprlock

Thank you to @PerchunPak for her work in #293

### CODE REVIEW

**Comment by 42Willow** [comment]
Fixes #295 

Config has been tested and is working

**Comment by 42Willow** [comment]
Oops, just realised this doesn’t actually use the hyperlink port at all, so I need to remove that from sources.json

The hyprlock port is only a configuration file? Why does it even exist when the [hyprland](https://github.com/catppuccin/hyprland) port is all you need?

**Review by getchoo — CHANGES_REQUESTED** [review]
This module should be enabled in `tests/home.nix`

**Comment by 42Willow** [comment]
> This module should be enabled in `tests/home.nix`

Should I disable the test in https://github.com/catppuccin/nix/blob/45745fe5960acaefef2b60f3455bcac6a0ca6bc9/tests/darwin.nix ?

**Review by getchoo — APPROVED** [review]
Sorry for the wait. Thanks!

**Pull request merged**
