### PR TITLE
feat(home-manager): init oh-my-posh

### PR DESCRIPTION
**Pull request by PerchunPak**

### CODE REVIEW

**Comment by PerchunPak** [comment]
I had to do

```nix
programs.oh-my-posh = {
  settings =
    { }
    // builtins.fromJSON (
      builtins.unsafeDiscardStringContext (
        builtins.readFile "${pkgs.oh-my-posh}/share/oh-my-posh/themes/catppuccin_${config.catppuccin.flavor}.omp.json"
      )
    );
};
```

Because `useTheme` is discarded if `configuration` is used. Don't know how to integrate it to this library

**Comment by PerchunPak** [comment]
Well...

https://github.com/JanDeDobbeleer/oh-my-posh/pull/6032#issuecomment-2550860542

**Review by isabelroses — COMMENTED** [review]
Hey, we just did a treewide change. Could you rebase and ajust your code to be inline with that, thanks ❤️

**Comment by getchoo** [comment]
Per our [contributing guide](https://github.com/catppuccin/nix/blob/72387df84ad52b0b54b98c3e72a62fa4a510413a/CONTRIBUTING.md):

> Unofficial ports will not be accepted

And even though this does use the official palette, oh-my-posh itself is not supported by the org. Sorry :(

**Pull request closed without merging**
