### PR TITLE
feat(home-manager): add support for fuzzel

### PR DESCRIPTION
**Pull request by SchweGELBin**
Added support for fuzzel.
Used ```xdg.configFile```, maybe there is a way to convert it to ```programs.fuzzel.settings.colors```.

### CODE REVIEW

**Comment by SchweGELBin** [comment]
Sorry, I wasn't aware of #75.

**Comment by SchweGELBin** [comment]
Now the border color is the accent color (with the help of catppuccin/palette).

**Comment by getchoo** [comment]
i would prefer to go with #75 as that (primarily) uses the upstream port over the full palette (which we consider to be a better practice)

**Comment by SchweGELBin** [comment]
I'm good with it, made this pr, because I didn't know it existed. If I can help, let me know.

**Comment by getchoo** [comment]
i've gone back and rebased the first PR, so closing this in favor of it

**Pull request closed without merging**
