### PR TITLE
feat(home-manager): add support for fuzzel

### PR DESCRIPTION
**Pull request by Anomalocaridid**
Adds support for fuzzel.

### CODE REVIEW

**Comment by Anomalocaridid** [comment]
Marking as draft because I realized I could add an accent option for the match text color, but it would require access to the palette brought in in #69 in order to translate the accent's color's name to its hex code.

**Comment by Anomalocaridid** [comment]
> is this something missing in upstream? it might be better contribute this there rather than use the palette.

It's not a missing color in the theme. I just figured the accent could replace `red` for the `match` and `selection-match` colors. I am not sure how that could be implemented upstream.

**Comment by getchoo** [comment]
this will need a rebase

**Comment by Anomalocaridid** [comment]
Apparently there is a fairly straightforward way I could implement the accent color upstream, thanks to the recent RFC for whiskers: https://github.com/catppuccin/community/blob/main/rfc/CAT-0003-Whiskers.md#matrix. I am going to take care of that first and then update this PR afterwards.

**Comment by getchoo** [comment]
rebased onto main. still waiting on https://github.com/catppuccin/fuzzel/pull/1

**Comment by Anomalocaridid** [comment]
Sorry, I was planning on taking care of rebasing myself once the changes to the fuzzel theme were merged.

**Comment by Anomalocaridid** [comment]
catppuccin/fuzzel#1 has finally been merged and I have updated this PR accordingly. I believe this is now ready for review.

**Review by getchoo — APPROVED** [review]
LGTM. Sorry for the wait!

**Comment by Anomalocaridid** [comment]
No worries. Thank you!

**Pull request merged**
